[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "securelend"
version = "1.0.0"
description = "SecureLend SDK for Python"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "httpx[http2]>=0.25.0"
]

[project.urls]
"Homepage" = "https://github.com/SecureLend/sdk/tree/main/packages/python"
"Bug Tracker" = "https://github.com/SecureLend/sdk/issues"
